name: Jakpost Popular Scraper

permissions:
  contents: write
  
on:
  schedule:
    - cron: "30 1 * * *"   # 08:30 WIB
    - cron: "30 9 * * *"   # 16:30 WIB
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: popular-csv
          path: popular.csv

      - name: Commit CSV to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add popular.csv
          git commit -m "update popular csv" || echo "no changes"

          git pull --rebase origin main
          git push
